### ISSUE TITLE
Zero features found from small PCAPs error

### ISSUE THREAD

**Issue by jspeed-meyers** [CyberReboot/NetworkML#462]
### Description
Using small PCAPs (e.g. 24 bytes) can result in this error: ERROR:networkml.utils.model:Failed because: Found array with 0 feature(s) (shape=(2594, 0)) while a minimum of 1 is required.

### Expected result
NetworkML should handle this cleanly and not throw an error.

**Comment by cglewis** [comment]
No longer reproducible with code rewrite.
