### ISSUE TITLE
networkml uses TCP/IP or UDP/IP only

### ISSUE THREAD

**Issue by anarkiwi** [CyberReboot/NetworkML#479]
networkml knows how to deal with only TCP or UDP. 

It doesn't know about non-IP traffic - for example, it doesn't know about IPX/SPX (http://jetdirect.printerdepo.com/en/hp-jetdirect-print-servers/embedded-web-server-v-38-xx/networking-tab/network-settings/ipxspx/#en_ww-table4.5) typically used by printers to advertise services - a strong signal for recognizing a printer. Even if there is no "conversation" or client using the printer's IPX-based services, just their presence is a signal that the device is probably a printer.

It also doesn't know about other non TCP/UDP services - for example it doesn't know about icmp6 RA (router advertisements) or RSTP (spanning tree) or LLDP/CDP (https://wiki.wireshark.org/CDP). Those are strong signals helping in recognizing a switch/router/SIP phone versus a host or server.

**Comment by cglewis** [comment]
This has been addressed in the rewrite.
