### ISSUE TITLE
Issue in standalone dev environment

### ISSUE THREAD

**Issue by jseparovic** [CyberReboot/NetworkML#559]
### Description
I'm having an issue with my initial testing using a dev environment setup.
`TypeError: can't pickle _thread.RLock objects` (see below for output). 
It doesn't seem to do anything after getting this error

### Environment
- Git commit hash = c2e24d600fffbb903fcb221ea117f097d4362810
- Operating system = CentOS Linux release 7.7.1908
- Conda:
```
(base) [root@docker2 ~]# conda info
     active environment : base
    active env location : /root/anaconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /root/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/3.10.0-1062.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Steps to reproduce
```
# setup dev environment
make dev
conda activate posml-dev

# remove installed networkml to use local source code instead
pip uninstall networkml

# capture some ip cam traffic (about 1 mins worth just for initial test, about 3500 packets. Will use 15 mins later on)
tcpdump -i eth1 host 192.168.1.59 -w gw1.pcap

# copy the start script to the base directory
cp bin/networkml run
```

### Expected result
Run eval on the pcap file
I read that Poseidon does a number of pre-processing steps on a standard pcap file, do I need to do this pre-processing for eval or is it just for training? Is there a utility I can use to do this outside of Poseidon?

### Actual result
````
(posml-dev) [root@d2 NetworkML]# LOG_LEVEL=DEBUG ./run -p /root/pcap
DEBUG:networkml.utils.common:RABBIT flag set to: False
DEBUG:networkml.utils.common:REDIS flag set to: False
DEBUG:networkml.utils.common:RABBIT flag set to: False
DEBUG:networkml.utils.common:REDIS flag set to: False
DEBUG:networkml.NetworkML:Loaded model from networkml/trained_models/onelayer/OneLayerModel.pkl
DEBUG:networkml.utils.common:RABBIT flag set to: False
DEBUG:networkml.utils.common:REDIS flag set to: False
DEBUG:networkml.utils.common:RABBIT flag set to: False
DEBUG:networkml.utils.common:REDIS flag set to: False
INFO:networkml.utils.model:no cache found, adding /root/pcap/gw1.pcap to be sessionized
Traceback (most recent call last):
  File "/root/anaconda3/envs/posml-dev/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/root/anaconda3/envs/posml-dev/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

**Comment by cglewis** [comment]
@jseparovic that's a bug with running it in python3.6. Updating to python3.7 will fix this issue.  However, it's something we should handle, so I'll keep this open and work on a quick patch. Will update here when it's ready.

**Comment by cglewis** [comment]
@jseparovic PR #560 addresses this (thanks @anarkiwi !) I’ll merge it in when the tests finish.  Feel free to reopen this if the problem persists with these changes.

**Comment by jseparovic** [comment]
@cglewis thanks for the fast response. Just on the data pre-processing for training, is there a specific utility from the Poseidon code base I can look at to understand how to transform a full pcap file into the processed pcap file required for training?

**Comment by jseparovic** [comment]
@cglewis Just noticed the Makefile dev target is pointing to 3.6, should this be 3.7 ?
https://github.com/CyberReboot/NetworkML/blob/master/Makefile#L93

**Comment by cglewis** [comment]
For cutting up a pcap for training that captured from more than one host, the easiest way is it to use something like `tshark -r input.pcap -w output.pcap -Y "eth.addr == <mac>" (replacing <mac> with the MAC address of the device in your PCAP you want to train with. 

Then name the output.pcap file to something like: `DevWorkstation-uniquename-Wed2350-n00.pcap` where DevWorkstation is the label (https://github.com/CyberReboot/NetworkML/blob/master/networkml/configs/label_assignments.json) of that device you want to train and the rest of the parts of the filename don't really matter, but let you keep track of different devices with the same role, date/time, and option to dedup overlap.

As for the Makefile, yes, you're right - would you be open to making a PR for that? Thanks.

**Comment by jseparovic** [comment]
@cglewis done https://github.com/CyberReboot/NetworkML/pull/561

**Comment by jseparovic** [comment]
@cglewis needed to also update posml-dev.yml as conda was taking the versions from there even after setting env create python=3.7

Here's a PR for the change https://github.com/CyberReboot/NetworkML/pull/562
```
(posml-dev) [root@d2 NetworkML]# python -V
Python 3.7.6
(posml-dev) [root@d2 NetworkML]# pip -V
pip 20.0.2 from /root/anaconda3/envs/posml-dev/lib/python3.7/site-packages/pip (python 3.7)
