### ISSUE TITLE
Is threshold_time missing from Model creation?

### ISSUE THREAD

**Issue by jseparovic** [CyberReboot/NetworkML#563]
Just wondering if the config property "threshold" should be passed during Model creation in NetworkML constructor.
```
        self.model = Model(duration=self.duration, hidden_size=None,
                           model_type=self.args.algorithm)
```
ie:
```
        self.model = Model(duration=self.duration, hidden_size=None,
                           model_type=self.args.algorithm, threshold_time=self.threshold)
```

I noticed that threshold_time is not passed to sessionizer (at least for the default args), and is always being set to 120 as a result of:
```
    if not threshold_time or threshold_time < 1:
        cfg_threshold = None
        threshold_time = cfg_threshold if cfg_threshold and cfg_threshold > 0 else 120
```

maybe this was intended? not sure

**Comment by cglewis** [comment]
@jseparovic That appears to be a bug from what I can tell. If you have a fix handy, I'd be happy to accept a PR, otherwise I'll try to get a fix in later this week.

**Comment by jseparovic** [comment]
@cglewis added https://github.com/CyberReboot/NetworkML/pull/565
