### ISSUE TITLE
Overhauling featurizer

### ISSUE THREAD

**Issue by lilchurro** [CyberReboot/NetworkML#84]
There are a number of features that aren't currently being considered when training the models that we should probably consider. In thinking about features we would like to keep and add, I think we should take the opportunity to reformat the featurizer script so that it's a bit more understandable and allows subsequent users the flexibility to add to, or use only a subset of, the features when they train their own models.

**GOALS:**
- Come up with a set of features to extract from traffic.
- Reorganize featurizer's output so that users can modularly understand what features have been extracted/processed, and select the features they would like to use for training.

**Comment by cglewis** [comment]
This is now doable using the `featurizer` to create functions of whatever features you want.
